<!DOCTYPE html>
<html lang="en">

<head>
    <?php require $config["PAGE"] . "meta" . DS  . "meta.phtml"; ?>
</head>

<body>
    <header>
        <?php require $config["PAGE"] . "components" . DS  . "nav_top.phtml"; ?>
    </header>
    <article>
        <div class="row">
            <div class="col-2"><?php require $config["PAGE"] . "components" . DS  . "nav_left.phtml"; ?></div>
            <div class="col-8">
                <div class="row">

                    <div class="col-12">
                        <p class="tm-txt-m tm-color-14">Homeowner / <label class="tm-color-15">Reservations</label>
                            <a href="#p_option" class="tm-lnk-0 tm-flt-r">
                                <img src="<?php echo $config["STATIC"] . "images/icons/icon-option2.png"; ?>" class="tm-icon-1">
                            </a>
                        </p>

                        <hr>
                        <div style="overflow-y: scroll; height: 100%">
                            <div class="row">
                                <div class="col-12">
                                    <p class="tm-color-14 tm-txt-m">Calendar:
                                        <label class="tm-color-15"><?php echo date('F', strtotime($year . "-" . $month)) . ", " . $year;  ?></label>
                                    </p>


                                </div>
                            </div>
                            <div class="row tm-shdw-0">
                                <div class="col-12">
                                    <div class="row">
                                        <?php for ($x = 1; $x <= $days; $x++) { ?>
                                            <script>
                                                function btn_<?php echo $x; ?>() {
                                                    document.getElementById('btn_<?php echo $x; ?>').click();
                                                }
                                            </script>
                                            <a href="#" onclick="btn_<?php echo $x; ?>();" class="tm-lnk-0">
                                                <div class="col-2 tm-curs-0">
                                                    <div class="row tm-shdw-0">
                                                        <div class="col-12">
                                                            <center>
                                                                <form action="?page=reservations" method="post">
                                                                    <p class="tm-color-0 tm-b-color-14 tm-txt-s tm-pd-3" style="width:30px; border-radius:20px;"> <?php echo $x; ?></p>
                                                                    <p class="tm-color-14 tm-txt-xs">
                                                                        <?php
                                                                        $day_stat =  mysqli_query($db_connection, ("SELECT * FROM reservations WHERE date = '" . $year . "-" . $month . "-" . $x . "' ORDER BY id DESC"
                                                                        ));
                                                                        $day_data = mysqli_fetch_array($day_stat);

                                                                        if ($year < date('Y', strtotime($current_date)) || $year == date('Y', strtotime($current_date)) && $month == date('m', strtotime($current_date)) && $x < date('d', strtotime($current_date))) { ?>

                                                                            <label class="tm-color-5">Unavailable</label>
                                                                        <?php } else { ?>

                                                                            <label class="tm-color-9">Available</label>
                                                                        <?php } ?>



                                                                    </p>
                                                                    <p class="tm-color-14 tm-txt-xs "><?php echo date('l', strtotime($year . "-" . $month . "-" . $x)) ?></p>
                                                                    <input type="hidden" name="id" value="<?php echo $year . "-" . $month . "-" . $x; ?>">
                                                                    <button type="submit" name="btn_view_days" id="btn_<?php echo $x; ?>" hidden></button>
                                                                </form>
                                                            </center>
                                                        </div>
                                                    </div>

                                                </div>
                                            </a>

                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
            <div class="col-2"><?php require $config["PAGE"] . "components" . DS  . "nav_right.phtml"; ?></div>
            <div class="tm-overlay" id="p_option">
                <div class="tm-popup">
                    <div class="row">
                        <div class="col-12">
                            <a href="#" class="tm-lnk-0  tm-b-color-12">
                                <img src="<?php echo $config["STATIC"] . "images/icons/icon-close.png"; ?>" class="tm-icon-1 tm-flt-r">
                                <p class="tm-color-3 tm-txt-m tm-flt-l">Reservations / <label class="tm-color-15">Options</label> </p>
                            </a>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12">
                            <a href="#p_date" class="tm-lnk-0  tm-b-color-12">
                                <img src="<?php echo $config["STATIC"] . "images/icons/icon-search.png"; ?>" class="tm-icon-1 tm-flt-l">
                                <p class="tm-color-3 tm-txt-s tm-flt-l">&nbsp; Calendar View</p>
                            </a>
                        </div>
                    </div>

                </div>

            </div>
            <div class="tm-overlay" id="p_date">
                <div class="tm-popup">
                    <form action="?page=reservations" method="post">

                        <div class="row">
                            <div class="col-12">
                                <a href="?page=reservations#p_option" class="tm-lnk-0  tm-b-color-12">
                                    <img src="<?php echo $config["STATIC"] . "images/icons/icon-close.png"; ?>" class="tm-icon-1 tm-flt-r">
                                    <p class="tm-color-3 tm-txt-m tm-flt-l">&nbsp; Calendar View</p>
                                </a>
                            </div>
                        </div>

                        <br>
                        <p class="tm-color-14 tm-txt-s">Choose Date*</p>
                        <input type="month" autocomplete="off" name="date" required class="tm-input-0 tm-bdr-0 tm-outline-0 tm-pd-3 tm-curs-0 tm-wd-full">
                        <hr>
                        <br>

                        <input type="submit" name="btn_calender_view" class=" tm-pd-3 tm-color-0 tm-b-color-15 tm-bdr-0 tm-outline-0  tm-txt-s tm-wd-full tm-curs-0" value="View">
                        <br>
                    </form>
                </div>
            </div>

            <?php if (isset($_SESSION["res_vid"]) &&  !empty($_SESSION["res_vid"])) { ?>

                <div class="tm-overlay" id="p_view_day">
                    <div class="tm-popup">

                        <div class="row">
                            <div class="col-12">
                                <a href="#" class="tm-lnk-0  tm-b-color-12">
                                    <img src="<?php echo $config["STATIC"] . "images/icons/icon-close.png"; ?>" class="tm-icon-1 tm-flt-r">
                                    <p class="tm-color-3 tm-txt-m tm-flt-l">&nbsp; Reservations / <label class="tm-color-15"><?php echo date('F d Y', strtotime($_SESSION["res_vid"]));  ?></label></p>
                                </a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">



                                <?php if ($year < date('Y', strtotime($current_date)) || $year == date('Y', strtotime($current_date)) && $month == date('m', strtotime($current_date)) && date('d', strtotime($_SESSION["res_vid"])) < date('d', strtotime($current_date))) { ?>
                                    <p class="tm-color-5 tm-txt-flt-c tm-txt-s">Unavailable!</p>
                                <?php } else { ?>

                                    <?php if ($res_flag == 0) { ?>
                                        <?php  ?>

                                        <br>
                                        <form action="?page=reservations" method="POST">
                                            <p class="tm-color-14 tm-txt-s">Type*</p>
                                            <select name="type" required class="tm-input-0 tm-bdr-0 tm-outline-0 tm-pd-3 tm-txt-s tm-wd-full"
                                                    onchange="showHideTime(this)">
                                                <option value="">--Select here--</option>
                                                <?php if ($option1 == 0) { ?>
                                                    <option value="Tennis Court">Tennis Court (Free)</option>
                                                <?php } ?>
                                                <?php if ($option2 == 0) { ?>
                                                    <option value="Basketball Court">Basketball Court (Free)</option>
                                                <?php } ?>
                                                <?php if ($option3 == 0 ) { ?>
                                                    <option value="Swimming Pool (Day Swimming)">Swimming Pool | Day Swimming 8:00 AM - 5:00 PM (P 5,000)</option>
                                                <?php } ?>
                                                <?php if ($option4 == 0 ) { ?>
                                                    <option value="Swimming Pool (Night Swimming)">Swimming Pool | Night Swimming 6:00 AM - 12:00 PM (P 6,000)</option>
                                                <?php } ?>
                                            </select>
                                            <hr>
                                            <br>
                                            <div id="time-range">
                                                <p class="tm-color-14 tm-txt-s">Schedule Time*</p>
                                                <input type="time" autocomplete="off" name="start_time" required class="tm-input-0 tm-bdr-0 tm-outline-0 tm-pd-3  tm-wd-full">
                                                <input type="time" autocomplete="off" name="end_time" required class="tm-input-0 tm-bdr-0 tm-outline-0 tm-pd-3  tm-wd-full">
                                                <hr>
                                                <br>
                                            </div>
                                            <p class="tm-color-14 tm-txt-s">Note</p>
                                            <textarea name="note" placeholder="Type here" class="tm-input-0 tm-bdr-0 tm-outline-0 tm-pd-3  tm-wd-full " cols="30" rows="10"></textarea>
                                            <hr>
                                            <br>
                                            <p class="tm-color-14 tm-txt-s"><input type="checkbox" required>Confirm Action*</p>
                                            <br>
                                            <input type="submit" name="btn_reserve" class=" tm-pd-3 tm-color-0 tm-b-color-15 tm-bdr-0 tm-outline-0  tm-txt-s tm-wd-full tm-curs-0" value="Reserve">
                                            <br>
                                        </form>
                                        
                                        <script type="text/javascript">
                                            function showHideTime(select) {
                                                const timeRange = document.getElementById('time-range');
                                                if (select.value === 'Swimming Pool (Day Swimming)' || select.value === 'Swimming Pool (Night Swimming)') {
                                                    timeRange.style.display= 'none';
                                                }
                                                else {
                                                    timeRange.style.display= 'block';
                                                }
                                            }
                                        </script>
                                        


                                        <?php ?>

                                    <?php } ?>

                                    <?php if ($res_flag == 2) { ?>


                                        <form action="?page=reservations" method="post">
                                            <div class="row">
                                                <div class="col-12">
                                                    <center>
                                                        <img src="<?php echo $config["STATIC"] . "images/icons/icon-info.png"; ?>" class="tm-icon-1 tm-flt-l">
                                                        <p class="tm-color-3 tm-txt-s tm-flt-l">&nbsp; Type: <?php echo $res_data["type"]; ?></p>
                                                    </center>

                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-12">
                                                    <center>
                                                        <img src="<?php echo $config["STATIC"] . "images/icons/icon-info.png"; ?>" class="tm-icon-1 tm-flt-l">
                                                        <p class="tm-color-3 tm-txt-s tm-flt-l">&nbsp; Schedule Time: <?php echo date('h:i A', strtotime($res_data["time"])); ?></p>
                                                    </center>

                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-12">
                                                    <center>
                                                        <img src="<?php echo $config["STATIC"] . "images/icons/icon-info.png"; ?>" class="tm-icon-1 tm-flt-l">
                                                        <p class="tm-color-3 tm-txt-s tm-flt-l">&nbsp; Amount To Pay: P <?php echo number_format($res_data["payment"], 2); ?></p>
                                                    </center>

                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-12">
                                                    <center>
                                                        <img src="<?php echo $config["STATIC"] . "images/icons/icon-info.png"; ?>" class="tm-icon-1 tm-flt-l">
                                                        <p class="tm-color-3 tm-txt-s tm-flt-l">&nbsp; Note: <?php echo $res_data["note"]; ?></p>
                                                    </center>

                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-12">
                                                    <center>
                                                        <img src="<?php echo $config["STATIC"] . "images/icons/icon-info.png"; ?>" class="tm-icon-1 tm-flt-l">
                                                        <p class="tm-color-3 tm-txt-s tm-flt-l">&nbsp; Feedback: <?php echo $res_data["feedback"]; ?></p>
                                                    </center>

                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-12">
                                                    <center>
                                                        <img src="<?php echo $config["STATIC"] . "images/icons/icon-info.png"; ?>" class="tm-icon-1 tm-flt-l">
                                                        <p class="tm-color-3 tm-txt-s tm-flt-l">&nbsp; Status: <?php echo $res_data["status"]; ?></p>
                                                    </center>

                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-12">
                                                    <center>
                                                        <img src="<?php echo $config["STATIC"] . "images/icons/icon-info.png"; ?>" class="tm-icon-1 tm-flt-l">
                                                        <p class="tm-color-3 tm-txt-s tm-flt-l">&nbsp; Created At: <?php echo $res_data["created_at"]; ?></p>
                                                    </center>

                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-12">
                                                    <center>
                                                        <img src="<?php echo $config["STATIC"] . "images/icons/icon-info.png"; ?>" class="tm-icon-1 tm-flt-l">
                                                        <p class="tm-color-3 tm-txt-s tm-flt-l">&nbsp; Updated At: <?php echo $res_data["updated_at"]; ?></p>
                                                    </center>

                                                </div>
                                            </div>
                                            <br>
                                            <p class="tm-color-14 tm-txt-s"><input type="checkbox" required>Confirm Action*</p>
                                            <br>
                                            <input type="submit" name="btn_cancel_res" class=" tm-pd-3 tm-color-0 tm-b-color-15 tm-bdr-0 tm-outline-0  tm-txt-s tm-wd-full tm-curs-0" value="Cancel Reservation">
                                            <br>
                                        </form>
                                    <?php } ?>


                                <?php } ?>



                            </div>
                        </div>


                    </div>
                </div>
            <?php } ?>
    </article>
</body>

</html>