<div class="row tm-b-color-14">
    <div class="col-4">
        <p class=" tm-txt-m tm-color-0 tm-pd-3 tm-txt-flt-c">Terms & Conditions</p>
        <p class=" tm-txt-s tm-color-0 tm-pd-3">By using this website, you declare that you have read and comprehend this Agreement. Accept its terms and obligations. We highly advise you to exit this Agreement before leaving the website if you do not wish to be bound by its terms.</p>
    </div>
    <div class="col-4">
        <p class=" tm-txt-m tm-color-0 tm-pd-3 tm-txt-flt-c">Privacy Policy</p>
        <p class=" tm-txt-s tm-color-0 tm-pd-3">If you use this website, you could be asked to provide confidential information. You are responsible for ensuring the accuracy of this information and for protecting the security and privacy of your personal data.</p>
    </div>
    <div class="col-4">
        <p class=" tm-txt-m tm-color-0 tm-pd-3 tm-txt-flt-c">About</p>
        <p class=" tm-txt-s tm-color-0 tm-pd-3"> For a subdivision, planned community, or condominium structure, a homeowner association (HOA) establishes and upholds rules helps to provide calendar, payments system, and communications system. To streamline interactions and keep track of payments.</p>
    </div>

    <div class="row">
        <div class="col-12">
            <p class="tm-txt-s tm-color-0 tm-pd-3 tm-txt-flt-c">Copyright © <?php echo date('Y', strtotime($current_date)); ?> HOA. All Rights Reserved</p>
        </div>
    </div>
</div>